name: at_utils
description: This is the Utility library for @protocol projects. It contains utility classes for atsign, atmetadata, configuration and logger.
version: 1.0.1+8
repository: https://github.com/atsign-foundation/at_tools
homepage: https://atsign.dev
publish_to: none

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  logging: ^0.11.4
  yaml: ^2.2.0
  crypto: ^3.0.0
  at_commons:
    git:
      url: https://github.com/atsign-foundation/at_tools.git
      path: at_commons
      ref: connection_issue
      version: ^1.0.1+8


dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
  test_process: ^1.0.5
